### ISSUE TITLE
Cant use it on Windows

### ISSUE THREAD

**Issue by yogeshhk** [tensorchord/modelz-llm#98]
Error:

Traceback (most recent call last):
  File "C:\Users\yoges\anaconda3\envs\genai\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\yoges\anaconda3\envs\genai\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\yoges\anaconda3\envs\genai\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yoges\anaconda3\envs\genai\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yoges\anaconda3\envs\genai\lib\site-packages\modelz_llm\uds.py", line 30, in __init__
    self.run()
  File "C:\Users\yoges\anaconda3\envs\genai\lib\site-packages\modelz_llm\uds.py", line 30, in __init__
    self.run()
  File "C:\Users\yoges\anaconda3\envs\genai\lib\site-packages\modelz_llm\uds.py", line 33, in run
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
  File "C:\Users\yoges\anaconda3\envs\genai\lib\site-packages\modelz_llm\uds.py", line 33, in run
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
AttributeError: module 'socket' has no attribute 'AF_UNIX'
AttributeError: module 'socket' has no attribute 'AF_UNIX'
Traceback (most recent call last):
  File "C:\Users\yoges\anaconda3\envs\genai\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yoges\anaconda3\envs\genai\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\yoges\anaconda3\envs\genai\Scripts\modelz-llm.exe\__main__.py", line 7, in <module>
  File "C:\Users\yoges\anaconda3\envs\genai\lib\site-packages\modelz_llm\cli.py", line 62, in main
    app = build_falcon_app(args)
  File "C:\Users\yoges\anaconda3\envs\genai\lib\site-packages\modelz_llm\falcon_service.py", line 128, in build_falcon_app
    raise RuntimeError("failed to start the service")
RuntimeError: failed to start the service

**Comment by kemingy** [comment]
We use Unix Domain Socket and fork which might not work on Windows.

**Comment by Jirito0** [comment]
> We use Unix Domain Socket and fork which might not work on Windows.

I have modified the uds.py and falcon_service.py to allow this to work on Windows

In this example, I specified the service to run on port 8888. You will need to ensure you initialize the API server while specifing port 8888 (or replace 8888 with 8000 in the following .py files): 

modelz-llm -m bigscience/bloomz-560m --device auto --port 8888



C:\Users\myuser\anaconda3\Lib\site-packages\modelz_llm\uds.py

```
import asyncio
import multiprocessing as mp
import pathlib
import pickle
import socket
import struct
from typing import Any
from typing import Tuple

from modelz_llm.log import logger


def run_server(tcp_address: Tuple[str, int], barrier: mp.Barrier, cls, **kwargs):
    proc = mp.get_context("spawn").Process(
        target=Server, args=(tcp_address, barrier, cls), kwargs=kwargs, daemon=True
    )
    proc.start()
    return proc


class Server:
    def __init__(self, port: int, barrier: mp.Barrier, cls, **kwargs):
        try:
            self.func = cls(**kwargs)
        finally:
            barrier.wait()
        self.port = port
        self.run()
        

    def run(self):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(('127.0.0.1', self.port))  # Use self.port instead of hard-coded 8888
            sock.listen()
            while True:
                conn, addr = sock.accept()
                with conn:
                    logger.info("connected to a client: '%s'", addr)
                    while True:
                        num_bytes = conn.recv(4)
                        if not num_bytes:
                            logger.info("cannot receive data")
                            break
                        num = struct.unpack("!I", num_bytes)[0]
                        data = conn.recv(num)
                        try:
                            req = pickle.loads(data)
                            resp = self.func(req)
                        except Exception as err:
                            logger.warning(err)
                            resp = err
                        data = pickle.dumps(resp, protocol=pickle.HIGHEST_PROTOCOL)
                        conn.sendall(struct.pack("!I", len(data)))
                        conn.sendall(data)

                    logger.info("closing the connection")


class Client:
    def __init__(self, port: int) -> None:
        self.port = port
        self.reader = self.writer = None

    async def request(self, req: Any) -> Any:
        if self.reader is None or self.writer is None:
            self.reader, self.writer = await asyncio.open_connection('127.0.0.1', self.port)

        data = pickle.dumps(req, protocol=pickle.HIGHEST_PROTOCOL)
        self.writer.write(struct.pack("!I", len(data)))
        self.writer.write(data)
        await self.writer.drain()

        num_bytes = await self.reader.read(4)
        num = struct.unpack("!I", num_bytes)[0]
        data = await self.reader.read(num)
        return pickle.loads(data)

    async def close(self):
        self.writer.close()
        await self.writer.wait_closed()

```


C:\Users\myuser\anaconda3\Lib\site-packages\modelz_llm\falcon_service.py

```
import argparse
import multiprocessing as mp
import time

import falcon
import msgspec
from falcon.asgi import App, Request, Response
from huggingface_hub import snapshot_download
from llmspec import (
    ChatCompletionRequest,
    EmbeddingRequest,
    ErrorResponse,
    PromptCompletionRequest,
)

from modelz_llm.emb import Emb
from modelz_llm.log import logger
from modelz_llm.model import LLM
from modelz_llm.uds import Client, run_server


class Ping:
    async def on_get(self, req: Request, resp: Response):
        resp.content_type = falcon.MEDIA_TEXT
        resp.text = "Modelz LLM service"


class ChatCompletions:
    def __init__(self, client: Client) -> None:
        self.client = client

    async def on_post(self, req: Request, resp: Response):
        buf = await req.stream.readall()
        try:
            chat_req = ChatCompletionRequest.from_bytes(buf=buf)
        except msgspec.ValidationError as err:
            logger.info(f"Failed to parse request: {err}")
            resp.status = falcon.HTTP_400
            resp.data = ErrorResponse.from_validation_err(err, str(buf)).to_json()
            return

        comp = await self.client.request(chat_req)
        logger.info(comp)
        if isinstance(comp, Exception):
            resp.status = falcon.HTTP_500
            resp.data = ErrorResponse.from_validation_err(
                comp, "internal error"
            ).to_json()
            return
        resp.data = comp.to_json()


class Completions:
    def __init__(self, client: Client) -> None:
        self.client = client

    async def on_post(self, req: Request, resp: Response):
        buf = await req.stream.readall()
        try:
            prompt_req = PromptCompletionRequest.from_bytes(buf=buf)
        except msgspec.ValidationError as err:
            logger.info(f"Failed to parse request: {err}")
            resp.status = falcon.HTTP_400
            resp.data = ErrorResponse.from_validation_err(err, str(buf)).to_json()
            return

        comp = await self.client.request(prompt_req)
        if isinstance(comp, Exception):
            resp.status = falcon.HTTP_500
            resp.data = ErrorResponse.from_validation_err(
                comp, "internal error"
            ).to_json()
            return
        resp.data = comp.to_json()


class Embeddings:
    def __init__(self, client: Client) -> None:
        self.client = client

    async def on_post(self, req: Request, resp: Response):
        buf = await req.stream.readall()
        try:
            embedding_req = EmbeddingRequest.from_bytes(buf=buf)
        except msgspec.ValidationError as err:
            logger.info(f"Failed to parse request: {err}")
            resp.status = falcon.HTTP_400
            resp.data = ErrorResponse.from_validation_err(err, str(buf)).to_json()
            return

        emb = await self.client.request(embedding_req)
        if isinstance(emb, Exception):
            resp.status = falcon.HTTP_500
            resp.data = ErrorResponse.from_validation_err(
                emb, "internal error"
            ).to_json()
            return
        resp.data = emb.to_json()


def build_falcon_app(args: argparse.Namespace):
    if args.dry_run:
        snapshot_download(repo_id=args.model)
        snapshot_download(repo_id=args.emb_model)
        return

# Adjusted to use the passed port argument
    llm_port = args.port
    emb_port = args.port + 1  # Using the next port for embeddings

    barrier = mp.get_context("spawn").Barrier(3)
    model_proc = run_server(llm_port, barrier, LLM, model_name=args.model, device=args.device)
    emb_proc = run_server(emb_port, barrier, Emb, model_name=args.emb_model, device=args.device)

    barrier.wait()
    time.sleep(1)
    if any(proc.exitcode is not None for proc in [model_proc, emb_proc]):
        raise RuntimeError("failed to start the service")

    llm_client = Client(llm_port)
    completion = Completions(llm_client)
    chat_completion = ChatCompletions(llm_client)
    emb_client = Client(emb_port)
    embeddings = Embeddings(emb_client)

    app = App()
    app.add_route("/", Ping())
    app.add_route("/completions", completion)
    app.add_route("/chat/completions", chat_completion)
    app.add_route("/embeddings", embeddings)
    app.add_route("/engines/{engine}/embeddings", embeddings)

    # Make it fully compatible with the current OpenAI API endpoints
    app.add_route("/v1/completions", completion)
    app.add_route("/v1/chat/completions", chat_completion)
    app.add_route("/v1/embeddings", embeddings)
    app.add_route("/v1/engines/{engine}/embeddings", embeddings)
    return app
```

**Comment by yogeshhk** [comment]
In the mean time, I started using LM Studio on Windows, but good to know about the above solution.
